### ISSUE TITLE
Introduce citation file

### ISSUE THREAD

**Issue by Reidmen** [finsberg/cardiac_benchmark#25]
For reference purposes (benchmark article) it would be ideal to include the `cff`.

**Comment by finsberg** [comment]
Good point! I guess we would like to cite the benchmark paper once we have a reference for it? Should we add something temporary, and update it once the benchmark paper is published?

**Comment by Reidmen** [comment]
I would think something temporary like the `cff` from [https://github.com/finsberg/ldrb/tree/main](ldrb) would work. I want to cite this repository within the benchmark article. Could you do that? 
It provides visibility and clarity for the future!

**Comment by finsberg** [comment]
@Reidmen  Fixed in https://github.com/finsberg/cardiac_benchmark/pull/26. Also bumped the version to 1.0
